### ISSUE TITLE
额，能问下有什么改进么

### ISSUE THREAD

**Issue by lwlizhe** [kaisengao/KsgLikeView#1]
掘金来的……
恕在下眼拙，有什么改进的地方么？

**Comment by kaisengao** [comment]
(✪ω✪)  请问哪里需要改进一下呢，处女文章好多地方不太熟悉。嘿嘿嘿

**Comment by lwlizhe** [comment]
额，文章中写到这个项目是对一般的like动画有改进，所以想问下改了哪些

**Comment by crazy1235** [comment]
https://github.com/kaisengao/KsgLikeView/blob/master/lib_likeview/src/main/java/com/kaisengao/likeview/like/KsgLikeView.java#L115

这个函数在每次点击飘出一个动画时，都会创建一个 ImageView对象。。。。。。建议最起码考虑一下复用。
